- Stands for Numerical Python and is the Core library for numerical computations
- Provides functionalities to make multi-dimensional arrays (1D, 2D, 3D or nD arrays)


- We have lists that we can use to create multi-dimensional lists instead of using arrays to perform these tasks, so why do we need Numpy?


- The advantages of using Numpy is Memory efficient, Faster, lot of convenience and functionalties.
- Numpy is built on C language which makes it so much faster.

Numpy contains `integers` and `floating point objects` and also some `containers like Lists and Dictionaries` built-in for faster mathematical calculations

# Numpy


<div>
<img src="attachment:Nd%20Arrays.png" width="500"/>
</div>

In NumPy, dimensions are called **axes**. In the 2-d array above, there are two axes, having two and three elements respectively. 

In NumPy terminology, for 2-D arrays:
* ```axis = 0``` refers to the axis running vertically downwards across rows
* ```axis = 1``` refers to the axis running horizontally across columns

<img src="numpy_axes.jpg" style="width: 600px; height: 400px">

## Import Numpy Package

In [ ]:
import numpy as np

### Memory comparisons of Lists and Numpy Arrays

In [ ]:
li_arr = [i for i in range(100)]
np_arr = np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
import sys

var1 = 10
print(sys.getsizeof(var1))  # Checking the size of one Python Variable

list1 = [10,20,30,40,50,60]
print(sys.getsizeof(list1)) # Checking the size of a list with some elements

28
104


In [ ]:
# Checking the memory that a list with 100 element occupies

import sys
print("Size of li_arr: " + str(sys.getsizeof(li_arr)) + "bytes")
print(sys.getsizeof(li_arr))

Size of li_arr: 904bytes
904


In [ ]:
# Checking the memory occupied by a numpy array containing 100 elements

print(np_arr.itemsize)
print(np_arr.size)
print(np_arr.itemsize * np_arr.size)

4
100
400


Now let's check for large values to see the real difference

In [ ]:
li_arr1 = [i for i in range(10000)]
np_arr1 = np.arange(10000)

print(sys.getsizeof(li_arr1))
print(np_arr1.itemsize * np_arr1.size)

87616
40000


### Let's see how fast a numpy array is, compared to a list

In [ ]:
#python lists
L = range(1000) #0 - 999
%timeit [i**2 for i in L]

354 µs ± 21 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
a = np.arange(1000)
%timeit a**2

2.26 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 1. Creating Numpy Arrays

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```, as done above
* Initialise arrays of fixed size (when the size is known) 

In [ ]:
import numpy as np

### <font color='maroon'>1.1 Manually creating numpy arrays</font>

In [ ]:
#Creating an array from a list
lst = [1,2,3,4]
arr_list = np.array(lst)

In [ ]:
lst1 = [10,20,30,40]
arr_list = np.array(lst1)

In [ ]:
arr_list

array([10, 20, 30, 40])

In [ ]:
arr_list2 = np.array([11,22,33,44])
arr_list2

array([11, 22, 33, 44])

In [ ]:
# Creating an array from a Tuple
tup = (1,2,3,4)
np.array(tup)

array([1, 2, 3, 4])

In [ ]:
# Pass tuple directly to create a numpy array
arr_tup = np.array((1,2,3,4))
arr_tup

array([1, 2, 3, 4])

In [ ]:
#Print Dimension of array 'arr_list'

arr_list.ndim

1

In [ ]:
# Print Shape of array 'arr_list'

arr_list.shape

(4,)

**<font color='blue'>Creating a 2-D Array</font>**

In [ ]:
# Creating a 2-D Array
#[[],[]]

arr_2d = np.array([[1,2,3,4], [4,5,6,7]]) # Lists within a List
arr_2d

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
arr2 = np.array([[1,2,3,4], [5,6,7,8]])  # list within a list
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(arr_2d.ndim)

2


In [ ]:
print(arr_2d.shape) # (rows,columns)

(2, 4)


**<font color='darkblue'> 1D Array is called Vector, 2D Array is called Matrix, nD Array is called Tensor </font>**

### <font color='maroon'>1.2  Creating arrays using functions</font>

The other common way is to initialise arrays using built-in functions. 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length
* ```np.diag()```: Constructs a diagonal array

In [ ]:
#using arange function
# arange is an array-valued version of the built-in Python range function

arr1 = np.arange(15) # 0.... n-1
arr1

In [ ]:
arr1 = np.arange(5,50,5)
arr1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr_step = np.arange(10,20) #start, end (exclusive), step
arr_step

In [ ]:
# Create an array of linearly spaced out values in the given range

arr_lin = np.linspace(0,50,9) #start, end, number of points
arr_lin

In [ ]:
arr3 = np.linspace(1,100,10)
arr3

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
arr_ones = np.ones((5,4))
arr_ones

In [ ]:
arr_ones = np.ones((3,9))
arr_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr_zero = np.zeros((5,5))
arr_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr_full = np.full((4,4),40)
arr_full

array([[40, 40, 40, 40],
       [40, 40, 40, 40],
       [40, 40, 40, 40],
       [40, 40, 40, 40]])

In [ ]:
arr_eye = np.eye(5)
arr_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#create array using diag function
arr_diag = np.diag([10,20,13,42]) #constructs a diagonal array.
arr_diag

In [ ]:
arr_diag = np.diag([11,23,45,67])
arr_diag

array([[11,  0,  0,  0],
       [ 0, 23,  0,  0],
       [ 0,  0, 45,  0],
       [ 0,  0,  0, 67]])

In [ ]:
# Extract diagonal values
np.diag(arr_diag)

In [ ]:
#create array using random
arr_random = np.random.random(5) 
arr_random

In [ ]:
arr_random = np.random.random(5)
arr_random

array([0.9988223 , 0.28528042, 0.34190392, 0.40757941, 0.27074575])

In [ ]:
adc = np.random.rand(4,3) 
adc

In [ ]:
arr_random2 = np.random.rand(5,4)
arr_random2

array([[0.61540814, 0.9833897 , 0.33432104, 0.25502344],
       [0.26633309, 0.44167434, 0.70076378, 0.43454167],
       [0.22180147, 0.68893376, 0.00358667, 0.80085822],
       [0.33986088, 0.34380181, 0.95622309, 0.49317069],
       [0.50579961, 0.42249043, 0.54174885, 0.97053626]])

## 2. Basic DataTypes

In [ ]:
a_int = np.arange(10, dtype='float')
a_int

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#You can explicitly specify which data-type you want:

a_float = np.arange(15, dtype='float')
a_float

In [ ]:
#The default data type is float for zeros and ones function

a = np.ones((3, 3), dtype='int')

print(a)
a.dtype

In [ ]:
np_zeros = np.zeros((5,5), dtype='int')
np_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**<font color='blue'>Some Other Datatypes in Numpy Arrays</font>**

In [ ]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [ ]:
b = np.array([True, False, True, False])  #Boolean datatype

b.dtype

dtype('bool')

In [ ]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

## <font color='maroon'>3. Indexing and Slicing</font>

### <font color='blue'>3.1 Indexing</font>

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**

<div>
<img src="attachment:Numpy1.png" width="450"/>
</div>

In [ ]:
arr = np.arange(10,20)
arr

In [ ]:
arr5 = np.arange(11,31)
arr5

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
arr5[5]

16

In [ ]:
# Print any element from the array by accessing it
print(arr[6])

In [ ]:
# For multidimensional arrays, indexes are tuples of integers:
arr_diag = np.diag([1, 2, 3])
arr_diag

In [ ]:
arr_diag = np.diag([10,20,30])
arr_diag

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [ ]:
arr_diag[1,1] = 50

In [ ]:
arr_diag

array([[10,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 30]])

In [ ]:
# Print the value at 2,2
print(arr_diag[2, 2])

In [ ]:
arr_diag[2, 1] = 33 #assigning value
arr_diag

### <font color='blue'>3.2 Slicing</font>

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr6 = np.arange(11,31)
arr6

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
arr6[5]

16

In [ ]:
arr6[5:18:2]  #[start:end:step]

array([16, 18, 20, 22, 24, 26, 28])

In [ ]:
arr[3:10:3] # [startindex: endindex(exclusive) : step]

In [ ]:
#we can also combine assignment and slicing:

arr_sl = np.arange(10)
arr_sl

In [ ]:
arr6

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [ ]:
arr6[0:6] = 1
arr6[6:] = 0

In [ ]:
arr6

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr_sl[:7] = 15
arr_sl[7:] = 16
arr_sl

In [ ]:
arr2 = np.arange(1,10,1)
arr2

<function ndarray.transpose>

In [ ]:
arr7 = np.arange(1,26,3).reshape(3,3)
arr7

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [ ]:
arr7[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[1:, 1:] = 12
arr2

In [ ]:
arr2[1:, 1:]

## <font color='maroon'>4. Numpy Numerical Operations</font>

### <font color='blue'>Basic Operations</font>

In [ ]:
scalar = np.array([1, 2, 3, 4])
scalar + 12.5

In [ ]:
arr8 = np.array([10,20,30,40])
arr8 * 2 

array([20, 40, 60, 80])

In [ ]:
arr8 ** 4

array([  10000,  160000,  810000, 2560000], dtype=int32)

All Arithmetic Operations happen Element-wise

In [ ]:
b = np.ones(4) + 2
b

In [ ]:
arr9 = np.array([2,3,4,5])
arr9

array([2, 3, 4, 5])

In [ ]:
arr8

array([10, 20, 30, 40])

In [ ]:
arr8 * arr9

array([ 20,  60, 120, 200])

In [ ]:
arr10 = np.arange(1,10).reshape(3,3)
arr11 = np.arange(10,19).reshape(3,3)

In [ ]:
arr10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr11

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
arr10 * arr11

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [ ]:
arr10.dot(arr11)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [ ]:
# Matrix Multiplication
arr1 = np.arange(1,10,1).reshape(3,3)
arr2 = np.arange(10,19,1).reshape(3,3)

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
print(arr1 * arr2) # Multiply the elements of both matrices

In [ ]:
arr1.dot(arr2) # Matrix multiplication 

### <font color='blue'>Comparisons</font>

In [ ]:
# Element-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.equal(a,b)

array([False,  True, False,  True])

In [ ]:
np.equal(a1,a2)

In [ ]:
# Array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 5])

np.array_equal(a,b)

False

In [ ]:
np.array_equal(a, c)

In [ ]:
np.array_equal(a1,a2)

#### Array Mathematics

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])

In [ ]:
arr1 + arr2

array([ 60,  80, 100, 120])

In [ ]:
np.add(arr1, arr2)

array([ 60,  80, 100, 120])

In [ ]:
arr2 - arr1

array([40, 40, 40, 40])

In [ ]:
np.subtract(arr1, arr2)

array([-40, -40, -40, -40])

In [ ]:
arr1 * arr2

array([ 500, 1200, 2100, 3200])

In [ ]:
np.multiply(arr1, arr2)

array([ 500, 1200, 2100, 3200])

In [ ]:
np.divide(arr1,arr2)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
arr1 / 10

array([1., 2., 3., 4.])

In [ ]:
# numpy additions
np.add(a, b)

In [ ]:
a + b

In [ ]:
# numpy subtraction
np.subtract(a,b)

In [ ]:
b-a

In [ ]:
np.divide(a,b)

In [ ]:
a / b

In [ ]:
np.multiply(a,b)

In [ ]:
a * b

In [ ]:
np.exp(b) # e**8

**Calculating Min, Mean, Median**

In [ ]:
arr1

array([10, 20, 30, 40])

In [ ]:
arr2

array([50, 60, 70, 80])

In [ ]:
np.mean(arr1)

25.0

In [ ]:
np.median(arr2)

65.0

In [ ]:
np.min(arr1)

10

In [ ]:
np.max(arr1)

40

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [ ]:
np.mean(a)   # Also a.mean()

In [ ]:
np.median(c)

In [ ]:
np.min(b)   # Also b.min()

In [ ]:
np.max(a)

In [ ]:
a.max()

In [ ]:
b.max()

### <font color='maroon'>Array Manipulation</font>

We have some ways to manipulate the arrays, these are - 

- numpy.concatenate(a,b)
- numpy.vstack(a,b)
- numpy.hstack(a,b)
- numpy.column_stack()
- numpy.hsplit()

Let's see one by one how they work

In [ ]:
arr1

array([10, 20, 30, 40])

In [ ]:
arr2

array([50, 60, 70, 80])

In [ ]:
arr3 = np.concatenate((arr1,arr2))

In [ ]:
arr3

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
np.mean(arr3)

45.0

In [ ]:
np.vstack((arr1,arr2))

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
np.hstack((arr1, arr2))

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
arr4 = np.column_stack((arr1, arr2))

In [ ]:
arr4

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [ ]:
arr4.ndim

2

In [ ]:
arr4.shape

(4, 2)

In [ ]:
arr4.flatten()

array([10, 50, 20, 60, 30, 70, 40, 80])

In [ ]:
arr5 = np.arange(16).reshape(4,4)

In [ ]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(arr5,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
x = np.arange(16).reshape(4, 4)
print(x)
np.hsplit(x,4)

### <font color='maroon'>Array Shape Manipulation</font>

**<font color='blue'>Reshaping</font>**

Reshape method does not change the shape of original array but returns a new array of the desired shape

In [ ]:
import numpy as np
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr6 = np.arange(24).reshape(8,3)

In [ ]:
arr6

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
b = b.reshape(2,3)
b

In [ ]:
at = np.arange(1,10).reshape(3,3)
at